branch-defaults:
  main:
    environment: cross-stitch-com-env

global:
  application_name: cross-stitch-com
  default_region: us-east-1
  default_ec2_keyname: aws-eb
  profile: null
  sc: null
